### ISSUE TITLE
It's not decompressing symlinks

### ISSUE THREAD

**Issue by piranna** [kevva/decompress-tar#4]
I have problems decompressing Linux kernel because symlinks like https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tree/arch/arm/boot/dts/include/dt-bindings?id=refs/tags/v4.3.3 are converted to empty files. I've found that [we are not filling the linkpath field](https://github.com/kevva/decompress-tar/blob/099f2423e552e43ddd673afcb0b3f9eecb3f81d6/index.js#L44-L50) nor the `symlink` type, that probably that's the reason why it's not working.

**Comment by kevva** [comment]
This was fixed in https://github.com/kevva/decompress-tar/commit/411bfb563e1ae9971869126f989ee19e4b4933ca.

**Comment by piranna** [comment]
:+1:
